apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: chaos-canary

spec:

  replicas: 5

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: chaos-canary

  template:

    metadata:
      labels:
        app: chaos-canary

    spec:

      containers:

        - name: chaos-canary

          image: chaos-canary:devv

          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: APP_NAME
              value: "Chaos Canary API"

            - name: APP_VERSION
              value: "v1"

            - name: ENVIRONMENT
              value: "Deployment" 
                  
          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 15
            periodSeconds: 10

  strategy:

    canary:

      stableService: chaos-canary-stable-service

      canaryService: chaos-canary-canary-service

      steps:

        - setWeight: 20

        - pause:
            duration: 30s

        - setWeight: 40

        - pause:
            duration: 30s

        - setWeight: 100