apiVersion: apps/v1
# tells kubernetes to manage this deployment 
kind: Deployment

metadata:
  name: chaos-canary-v2

spec:
# should always keep 2 pods alive for backup but for canary release we are currently using 1 replica  
  replicas: 1

  selector:
    matchLabels:
      app: chaos-canary
      version: v2

  template: 
    metadata:
# tells server to look for pods named chaos-canary kinda like hashtags 
      labels:
        app: chaos-canary
        version: v2

    spec:
      containers:
      - name: chaos-canary
        # use our docker image 
        image: chaos-canary:v2
# we are using local image so there is no need to pull image from docker hub 
        imagePullPolicy: Never
        env: 
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: chaos-canary-config 
              key: APP_NAME

        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: chaos-canary-config
              key: APP_VERSION
        - name: ENVIRONMENT
          valueFrom: 
            configMapKeyRef:
              name: chaos-canary-config
              key: ENVIRONMENT          

        ports:
        - containerPort: 8000

        # readiness probe 
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        # Liveness Probe 
        livenessProbe:
          httpGet: 
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
