apiVersion: apps/v1
# tells kubernetes to manage this deployment 
kind: Deployment

metadata:
  name: chaos-canary

spec:
# should always keep 2 pods alive for backup 
  replicas: 2

  selector:
    matchLabels:
      app: chaos-canary

  template: 
    metadata:
# tells server to look for pods named chaos-canary kinda like hashtags 
      labels:
        app: chaos-canary

    spec:
      containers:
      - name: chaos-canary
        # use our docker image 
        image: chaos-canary:v1
# we are using local image so there is no need to pull image from docker hub 
        imagePullPolicy: Never

        ports:
        - containerPort: 8000
