apiVersion: v1
kind: Service

metadata:
  name: chaos-canary-v2-service

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"

spec:
  type: NodePort

  selector:
    app: chaos-canary
    version: v2

  ports:
    - port: 80
      targetPort: 8000