# A service provides a stable endpoint for clients .
# it load-balances traffic to healthy pods so clients never communicate with pods directly.
apiVersion: v1
kind : Service

metadata:
  name: chaos-canary-service
  
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"

spec:

  selector:
    app: chaos-canary

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000

  type: NodePort
